use sdl2::keyboard::Scancode;

pub const All_MOUSE_BUTTONS: [u32; 32] = [
    1 << 0,
    1 << 1,
    1 << 2,
    1 << 3,
    1 << 4,
    1 << 5,
    1 << 6,
    1 << 7,
    1 << 8,
    1 << 9,
    1 << 10,
    1 << 11,
    1 << 12,
    1 << 13,
    1 << 14,
    1 << 15,
    1 << 16,
    1 << 17,
    1 << 18,
    1 << 19,
    1 << 20,
    1 << 21,
    1 << 22,
    1 << 23,
    1 << 24,
    1 << 25,
    1 << 26,
    1 << 27,
    1 << 28,
    1 << 29,
    1 << 30,
    1 << 31,
];

pub const ALL_SCANCODES: [Scancode; 241] = [
    Scancode::A,
    Scancode::B,
    Scancode::C,
    Scancode::D,
    Scancode::E,
    Scancode::F,
    Scancode::G,
    Scancode::H,
    Scancode::I,
    Scancode::J,
    Scancode::K,
    Scancode::L,
    Scancode::M,
    Scancode::N,
    Scancode::O,
    Scancode::P,
    Scancode::Q,
    Scancode::R,
    Scancode::S,
    Scancode::T,
    Scancode::U,
    Scancode::V,
    Scancode::W,
    Scancode::X,
    Scancode::Y,
    Scancode::Z,
    Scancode::Num1,
    Scancode::Num2,
    Scancode::Num3,
    Scancode::Num4,
    Scancode::Num5,
    Scancode::Num6,
    Scancode::Num7,
    Scancode::Num8,
    Scancode::Num9,
    Scancode::Num0,
    Scancode::Return,
    Scancode::Escape,
    Scancode::Backspace,
    Scancode::Tab,
    Scancode::Space,
    Scancode::Minus,
    Scancode::Equals,
    Scancode::LeftBracket,
    Scancode::RightBracket,
    Scancode::Backslash,
    Scancode::NonUsHash,
    Scancode::Semicolon,
    Scancode::Apostrophe,
    Scancode::Grave,
    Scancode::Comma,
    Scancode::Period,
    Scancode::Slash,
    Scancode::CapsLock,
    Scancode::F1,
    Scancode::F2,
    Scancode::F3,
    Scancode::F4,
    Scancode::F5,
    Scancode::F6,
    Scancode::F7,
    Scancode::F8,
    Scancode::F9,
    Scancode::F10,
    Scancode::F11,
    Scancode::F12,
    Scancode::PrintScreen,
    Scancode::ScrollLock,
    Scancode::Pause,
    Scancode::Insert,
    Scancode::Home,
    Scancode::PageUp,
    Scancode::Delete,
    Scancode::End,
    Scancode::PageDown,
    Scancode::Right,
    Scancode::Left,
    Scancode::Down,
    Scancode::Up,
    Scancode::NumLockClear,
    Scancode::KpDivide,
    Scancode::KpMultiply,
    Scancode::KpMinus,
    Scancode::KpPlus,
    Scancode::KpEnter,
    Scancode::Kp1,
    Scancode::Kp2,
    Scancode::Kp3,
    Scancode::Kp4,
    Scancode::Kp5,
    Scancode::Kp6,
    Scancode::Kp7,
    Scancode::Kp8,
    Scancode::Kp9,
    Scancode::Kp0,
    Scancode::KpPeriod,
    Scancode::NonUsBackslash,
    Scancode::Application,
    Scancode::Power,
    Scancode::KpEquals,
    Scancode::F13,
    Scancode::F14,
    Scancode::F15,
    Scancode::F16,
    Scancode::F17,
    Scancode::F18,
    Scancode::F19,
    Scancode::F20,
    Scancode::F21,
    Scancode::F22,
    Scancode::F23,
    Scancode::F24,
    Scancode::Execute,
    Scancode::Help,
    Scancode::Menu,
    Scancode::Select,
    Scancode::Stop,
    Scancode::Again,
    Scancode::Undo,
    Scancode::Cut,
    Scancode::Copy,
    Scancode::Paste,
    Scancode::Find,
    Scancode::Mute,
    Scancode::VolumeUp,
    Scancode::VolumeDown,
    Scancode::KpComma,
    Scancode::KpEqualsAS400,
    Scancode::International1,
    Scancode::International2,
    Scancode::International3,
    Scancode::International4,
    Scancode::International5,
    Scancode::International6,
    Scancode::International7,
    Scancode::International8,
    Scancode::International9,
    Scancode::Lang1,
    Scancode::Lang2,
    Scancode::Lang3,
    Scancode::Lang4,
    Scancode::Lang5,
    Scancode::Lang6,
    Scancode::Lang7,
    Scancode::Lang8,
    Scancode::Lang9,
    Scancode::AltErase,
    Scancode::SysReq,
    Scancode::Cancel,
    Scancode::Clear,
    Scancode::Prior,
    Scancode::Return2,
    Scancode::Separator,
    Scancode::Out,
    Scancode::Oper,
    Scancode::ClearAgain,
    Scancode::CrSel,
    Scancode::ExSel,
    Scancode::Kp00,
    Scancode::Kp000,
    Scancode::ThousandsSeparator,
    Scancode::DecimalSeparator,
    Scancode::CurrencyUnit,
    Scancode::CurrencySubUnit,
    Scancode::KpLeftParen,
    Scancode::KpRightParen,
    Scancode::KpLeftBrace,
    Scancode::KpRightBrace,
    Scancode::KpTab,
    Scancode::KpBackspace,
    Scancode::KpA,
    Scancode::KpB,
    Scancode::KpC,
    Scancode::KpD,
    Scancode::KpE,
    Scancode::KpF,
    Scancode::KpXor,
    Scancode::KpPower,
    Scancode::KpPercent,
    Scancode::KpLess,
    Scancode::KpGreater,
    Scancode::KpAmpersand,
    Scancode::KpDblAmpersand,
    Scancode::KpVerticalBar,
    Scancode::KpDblVerticalBar,
    Scancode::KpColon,
    Scancode::KpHash,
    Scancode::KpSpace,
    Scancode::KpAt,
    Scancode::KpExclam,
    Scancode::KpMemStore,
    Scancode::KpMemRecall,
    Scancode::KpMemClear,
    Scancode::KpMemAdd,
    Scancode::KpMemSubtract,
    Scancode::KpMemMultiply,
    Scancode::KpMemDivide,
    Scancode::KpPlusMinus,
    Scancode::KpClear,
    Scancode::KpClearEntry,
    Scancode::KpBinary,
    Scancode::KpOctal,
    Scancode::KpDecimal,
    Scancode::KpHexadecimal,
    Scancode::LCtrl,
    Scancode::LShift,
    Scancode::LAlt,
    Scancode::LGui,
    Scancode::RCtrl,
    Scancode::RShift,
    Scancode::RAlt,
    Scancode::RGui,
    Scancode::Mode,
    Scancode::AudioNext,
    Scancode::AudioPrev,
    Scancode::AudioStop,
    Scancode::AudioPlay,
    Scancode::AudioMute,
    Scancode::MediaSelect,
    Scancode::Www,
    Scancode::Mail,
    Scancode::Calculator,
    Scancode::Computer,
    Scancode::AcSearch,
    Scancode::AcHome,
    Scancode::AcBack,
    Scancode::AcForward,
    Scancode::AcStop,
    Scancode::AcRefresh,
    Scancode::AcBookmarks,
    Scancode::BrightnessDown,
    Scancode::BrightnessUp,
    Scancode::DisplaySwitch,
    Scancode::KbdIllumToggle,
    Scancode::KbdIllumDown,
    Scancode::KbdIllumUp,
    Scancode::Eject,
    Scancode::Sleep,
    Scancode::App1,
    Scancode::App2,
    Scancode::Num,
];