#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

/* automatically generated by rust-bindgen 0.71.1 */

pub const shaderc_compilation_status_shaderc_compilation_status_success:
    shaderc_compilation_status = 0;
pub const shaderc_compilation_status_shaderc_compilation_status_invalid_stage:
    shaderc_compilation_status = 1;
pub const shaderc_compilation_status_shaderc_compilation_status_compilation_error:
    shaderc_compilation_status = 2;
pub const shaderc_compilation_status_shaderc_compilation_status_internal_error:
    shaderc_compilation_status = 3;
pub const shaderc_compilation_status_shaderc_compilation_status_null_result_object:
    shaderc_compilation_status = 4;
pub const shaderc_compilation_status_shaderc_compilation_status_invalid_assembly:
    shaderc_compilation_status = 5;
pub const shaderc_compilation_status_shaderc_compilation_status_validation_error:
    shaderc_compilation_status = 6;
pub const shaderc_compilation_status_shaderc_compilation_status_transformation_error:
    shaderc_compilation_status = 7;
pub const shaderc_compilation_status_shaderc_compilation_status_configuration_error:
    shaderc_compilation_status = 8;
pub type shaderc_compilation_status = ::std::os::raw::c_int;
