// DO NOT COMMIT CHANGES TO THIS FILE.
// DO NOT MODIFY THIS FILE.
// 
// THE CONTENTS OF THIS FILE ARE AUTOMATICALLY GENERATED BY `build.rs`.
// 
// I highly recommend you run the following git command:
// git update-index --assume-unchanged crates/ris_data/src/info/build_info.rs
// 
// Doc: https://git-scm.com/docs/git-update-index#_using_assume_unchanged_bit

use std::fmt;

#[derive(Clone, Eq, PartialEq, Hash, Debug)]
pub struct BuildInfo {
    git_repo: String,
    git_commit: String,
    git_branch: String,
    rustc_version: String,
    build_date: String,
}

pub fn build_info() -> BuildInfo {
    BuildInfo {
        git_repo: String::from("https://github.com/Rismosch/ris_engine.git"),
        git_commit: String::from("3567bd8"),
        git_branch: String::from("main"),
        rustc_version: String::from("rustc 1.61.0 (fe5b13d68 2022-05-18)"),
        build_date: String::from("2022-08-20 11:07:19.183966 UTC"),
    }
}

impl fmt::Display for BuildInfo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        writeln!(f, "Build")?;
        writeln!(f, "git repo:      {}", self.git_repo)?;
        writeln!(f, "git commit:    {}", self.git_commit)?;
        writeln!(f, "git branch:    {}", self.git_branch)?;
        writeln!(f, "rustc version: {}", self.rustc_version)?;
        writeln!(f, "build date:    {}", self.build_date)?;

        Ok(())
    }
}
